### ISSUE TITLE
If several UIs share some pictures, does it support setting the pictures to be automatically generated in the public folder when importing them?

### ISSUE THREAD

**Issue by kane9527-e** [kyubuns/AkyuiUnity#38]
If several UIs share some pictures, does it support setting the pictures to be automatically generated in the public folder when importing them?
And akyuiimportsettings What is aky?

**Comment by kyubuns** [comment]
Sorry for the late reply.

> If several UIs share some pictures, does it support setting the pictures to be automatically generated in the public folder when importing them?

No.
You can do this by creating your own Trigger.
This will have to be prepared by each of you, since the issue of which sprite atlas to include the commonized sprites in will be a problem.

> And akyuiimportsettings What is aky?

Aky-ui is an intermediate file.
(It may not have been necessary for AkyuiImportSettings to be visible to the user.)
After generating the aky-ui file from the XD file, it is converted to Unity Prefab.
